//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.NuGet.Build.Tasks.Tests.Content {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.NuGet.Build.Tasks.Tests.Content.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;locked&quot;: false,
        ///  &quot;version&quot;: 2,
        ///  &quot;targets&quot;: {
        ///    &quot;.NETFramework,Version=v4.5.2&quot;: {
        ///      &quot;TestPackage/1.0.0&quot;: {
        ///        &quot;type&quot;: &quot;package&quot;,
        ///        &quot;contentFiles&quot;: {
        ///          &quot;contentFiles/cs/net45/ContentFolder/Content.txt&quot;: {
        ///            &quot;buildAction&quot;: &quot;Content&quot;,
        ///            &quot;codeLanguage&quot;: &quot;cs&quot;,
        ///            &quot;copyToOutput&quot;: false
        ///          }
        ///        }
        ///      }
        ///    }
        ///  },
        ///  &quot;libraries&quot;: {
        ///    &quot;TestPackage/1.0.0&quot;: {
        ///      &quot;sha512&quot;: &quot;4vvAtzBLtRb7vQOXlqu101Ea3uveI6vOoPz9WG88G3IJEWyKBy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LockFileWithBuildActionForCSharp {
            get {
                return ResourceManager.GetString("LockFileWithBuildActionForCSharp", resourceCulture);
            }
        }
    }
}
